# Generated by Django 5.2 on 2025-04-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
